//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShreeFabricators
{
    using System;
    using System.Collections.Generic;
    
    public partial class totalbill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public totalbill()
        {
            this.panelboxbills = new HashSet<panelboxbill>();
        }
    
        public int InvoiceNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TotalPanelBoxes { get; set; }
        public Nullable<int> TaxableAmount { get; set; }
        public Nullable<double> Sgst { get; set; }
        public Nullable<double> Cgst { get; set; }
        public Nullable<double> TotalTax { get; set; }
        public Nullable<double> NetPayable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<panelboxbill> panelboxbills { get; set; }
    }
}
